### PR TITLE
HW1, HW2, and HW3 updates

### PR DESCRIPTION
**Pull request by sabarevasan**
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by SidraBushra** [comment]
Product and Product_Category are already did by Thomas in the logical model, you didn't have to select those, and your relationship and primary keys in the customer and customer_purchase table is good.

**Comment by SidraBushra** [comment]
For HW2, For the Where query task,  you need to write order by command in the end, others queries are correct.

**Comment by SidraBushra** [comment]
For HW3, You don't need to make it a nested query, you only have to make a join and mention primary keys, and on Date Query, put month, year in group by command.

**Comment by sabarevasan** [comment]
@SidraBushra thank you. Should I make the updates you mentioned and request review to finalize my submission, for an approved PR??

**Pull request merged**
